### ISSUE TITLE
Beautify

### ISSUE THREAD

**Issue by coIorbIind** [OlegYurchik/fast-grpc#2]
Привет! Из твоей статьи на хабре узнал про данную библиотеку, и она меня очень заинтересовала. Увидев TODO лист в README захотелось оказать посильную помощь и поддержку. Я исправил генерацию .proto файла, теперь файл выглядит привлекательно 
![image](https://github.com/OlegYurchik/fast-grpc/assets/91391687/80e9ab23-6c0a-41f9-8685-aeeeed2b2edf)
изменил запуск advanced_greater'а с event_loop на запуск метода объект app, немного отрефакторил parse_type и убрал ошибку после вызова KeyboardInterrupt. Хотел бы поделиться своим PR'ом, но у меня нет прав сделать git push. Продолжай в том же духе!

**Comment by OlegYurchik** [comment]
Привет! Здорово, я очень рад, что тебя заинтересовала эта библиотека и ты помог решить одну из важных проблем)
Создать PR можно через Fork на github-e
